### ISSUE TITLE
Have any negative prompt template ?

### ISSUE THREAD

**Issue by wastu01** [Dalabad/stable-diffusion-prompt-templates#4]
It will be nice

**Comment by cleverestx** [comment]
This would be very nice too.

If anyone is home?

**Comment by wastu01** [comment]
@Dalabad any update ?

**Comment by arboeh** [comment]
I just thought the same :-)

**Comment by wastu01** [comment]
+1

**Comment by Dalabad** [comment]
Hey guys, negative prompts are - in my experience - very specific for an image. You start with a prompt and once you found a seed that you like, you fix that seed and you can improve on that specific case by adding positive / negative prompts.

There are the obvious ones like `ugly, malformed, text, copyright, signature, ...`, but I would not suggest using them on all images unless you think they are necessary. If you guys have experiences where some negative prompts always make sense, let me know :)

**Comment by wastu01** [comment]
Got it !
